name: batch_3_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  google_fonts: ^6.1.0
  http: ^1.1.2
  provider: ^6.1.1
  rating_dialog: ^2.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
